<a href="https://colab.research.google.com/github/pvpkrp/GIT_Practice/blob/new/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snc
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

In [9]:
#Download the data
!wget "https://docs.google.com/uc?export=download&id=1oJbdRpTLqPu1SIBXHkzWRaLaZbvZot7w" -O train.csv

--2024-09-20 15:30:43--  https://docs.google.com/uc?export=download&id=1oJbdRpTLqPu1SIBXHkzWRaLaZbvZot7w
Resolving docs.google.com (docs.google.com)... 173.194.217.138, 173.194.217.139, 173.194.217.113, ...
Connecting to docs.google.com (docs.google.com)|173.194.217.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1oJbdRpTLqPu1SIBXHkzWRaLaZbvZot7w&export=download [following]
--2024-09-20 15:30:43--  https://drive.usercontent.google.com/download?id=1oJbdRpTLqPu1SIBXHkzWRaLaZbvZot7w&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 74.125.141.132, 2607:f8b0:400c:c06::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|74.125.141.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38011 (37K) [application/octet-stream]
Saving to: ‘train.csv’

train.csv           100%[===================>]  37.12K  --.-KB/s    in 0s

2024-09-20 15:30:46 (88.6 MB/s) - ‘train.csv’ saved [38011/38011]

In [10]:
!ls -lrt

total 308
-rw-r--r-- 1 root root 38011 Jan 10  2022  train.csv
drwxr-xr-x 1 root root  4096 Sep 18 13:25  sample_data
-rw-r--r-- 1 root root 89177 Sep 20 15:25 'view?usp=sharing'
-rw-r--r-- 1 root root 89413 Sep 20 15:27 'view?usp=sharing.1'
-rw-r--r-- 1 root root 89324 Sep 20 15:27 'view?usp=sharing.2'

In [11]:
!cat train.csv

Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
LP001002,Male,No,0,Graduate,No,5849,0,,360,1,Urban,Y
LP001003,Male,Yes,1,Graduate,No,4583,1508,128,360,1,Rural,N
LP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y
LP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y
LP001008,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y
LP001011,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y
LP001013,Male,Yes,0,Not Graduate,No,2333,1516,95,360,1,Urban,Y
LP001014,Male,Yes,3+,Graduate,No,3036,2504,158,360,0,Semiurban,N
LP001018,Male,Yes,2,Graduate,No,4006,1526,168,360,1,Urban,Y
LP001020,Male,Yes,1,Graduate,No,12841,10968,349,360,1,Semiurban,N
LP001024,Male,Yes,2,Graduate,No,3200,700,70,360,1,Urban,Y
LP001027,Male,Yes,2,Graduate,,2500,1840,109,360,1,Urban,Y
LP001028,Male,Yes,2,Graduate,No,3073,8106,200,360,1,Urban,Y
LP001029,Male,No,0,Graduate,No,1853,2840,114,360,1,Rural,N
LP001030,Male,Yes,2,Graduate,No,1299,1086,17,120,1,Urban,Y
LP001032,Male,No,0,Graduate,No,4950,0,125,360,1,Urban,Y
LP001034,Male,No,1,Not Graduate,No,3596,0,100,240,,Urban,Y
LP001036,Female,No,0,Graduate,No,3510,0,76,360,0,Urban,N
LP001038,Male,Yes,0,Not Graduate,No,4887,0,133,360,1,Rural,N
LP001041,Male,Yes,0,Graduate,,2600,3500,115,,1,Urban,Y
LP001043,Male,Yes,0,Not Graduate,No,7660,0,104,360,0,Urban,N
LP001046,Male,Yes,1,Graduate,No,5955,5625,315,360,1,Urban,Y
LP001047,Male,Yes,0,Not Graduate,No,2600,1911,116,360,0,Semiurban,N
LP001050,,Yes,2,Not Graduate,No,3365,1917,112,360,0,Rural,N
LP001052,Male,Yes,1,Graduate,,3717,2925,151,360,,Semiurban,N
LP001066,Male,Yes,0,Graduate,Yes,9560,0,191,360,1,Semiurban,Y
LP001068,Male,Yes,0,Graduate,No,2799,2253,122,360,1,Semiurban,Y
LP001073,Male,Yes,2,Not Graduate,No,4226,1040,110,360,1,Urban,Y
LP001086,Male,No,0,Not Graduate,No,1442,0,35,360,1,Urban,N
LP001087,Female,No,2,Graduate,,3750,2083,120,360,1,Semiurban,Y
LP001091,Male,Yes,1,Graduate,,4166,3369,201,360,,Urban,N
LP001095,Male,No,0,Graduate,No,3167,0,74,360,1,Urban,N
LP001097,Male,No,1,Graduate,Yes,4692,0,106,360,1,Rural,N
LP001098,Male,Yes,0,Graduate,No,3500,1667,114,360,1,Semiurban,Y
LP001100,Male,No,3+,Graduate,No,12500,3000,320,360,1,Rural,N
LP001106,Male,Yes,0,Graduate,No,2275,2067,,360,1,Urban,Y
LP001109,Male,Yes,0,Graduate,No,1828,1330,100,,0,Urban,N
LP001112,Female,Yes,0,Graduate,No,3667,1459,144,360,1,Semiurban,Y
LP001114,Male,No,0,Graduate,No,4166,7210,184,360,1,Urban,Y
LP001116,Male,No,0,Not Graduate,No,3748,1668,110,360,1,Semiurban,Y
LP001119,Male,No,0,Graduate,No,3600,0,80,360,1,Urban,N
LP001120,Male,No,0,Graduate,No,1800,1213,47,360,1,Urban,Y
LP001123,Male,Yes,0,Graduate,No,2400,0,75,360,,Urban,Y
LP001131,Male,Yes,0,Graduate,No,3941,2336,134,360,1,Semiurban,Y
LP001136,Male,Yes,0,Not Graduate,Yes,4695,0,96,,1,Urban,Y
LP001137,Female,No,0,Graduate,No,3410,0,88,,1,Urban,Y
LP001138,Male,Yes,1,Graduate,No,5649,0,44,360,1,Urban,Y
LP001144,Male,Yes,0,Graduate,No,5821,0,144,360,1,Urban,Y
LP001146,Female,Yes,0,Graduate,No,2645,3440,120,360,0,Urban,N
LP001151,Female,No,0,Graduate,No,4000,2275,144,360,1,Semiurban,Y
LP001155,Female,Yes,0,Not Graduate,No,1928,1644,100,360,1,Semiurban,Y
LP001157,Female,No,0,Graduate,No,3086,0,120,360,1,Semiurban,Y
LP001164,Female,No,0,Graduate,No,4230,0,112,360,1,Semiurban,N
LP001179,Male,Yes,2,Graduate,No,4616,0,134,360,1,Urban,N
LP001186,Female,Yes,1,Graduate,Yes,11500,0,286,360,0,Urban,N
LP001194,Male,Yes,2,Graduate,No,2708,1167,97,360,1,Semiurban,Y
LP001195,Male,Yes,0,Graduate,No,2132,1591,96,360,1,Semiurban,Y
LP001197,Male,Yes,0,Graduate,No,3366,2200,135,360,1,Rural,N
LP001198,Male,Yes,1,Graduate,No,8080,2250,180,360,1,Urban,Y
LP001199,Male,Yes,2,Not Graduate,No,3357,2859,144,360,1,Urban,Y
LP001205,Male,Yes,0,Graduate,No,2500,3796,120,360,1,Urban,Y
LP001206,Male,Yes,3+,Graduate,No,3029,0,99,360,1,Urban,Y
LP001207,Male,Yes,0,Not Graduate,Yes,2609,3449,165,180,0,Rural,N
LP001213,Male,Yes,1,Graduate,No,4945,0,,360,0,Rural,N
LP001222,Female,No,0,Graduate,No,4166,0,116,360,0,Semiurban,N
LP001225,Male,Yes,0,Graduate,No,5726,4595,258,360,1,Semiurban,N
LP001228,Male,No,0,Not Graduate,No,3200,2254,126,180,0,Urban,N
LP001233,Male,Yes,1,Graduate,No,10750,0,312,360,1,Urban,Y
LP001238,Male,Yes,3+,Not Graduate,Yes,7100,0,125,60,1,Urban,Y
LP001241,Female,No,0,Graduate,No,4300,0,136,360,0,Semiurban,N
LP001243,Male,Yes,0,Graduate,No,3208,3066,172,360,1,Urban,Y
LP001245,Male,Yes,2,Not Graduate,Yes,1875,1875,97,360,1,Semiurban,Y
LP001248,Male,No,0,Graduate,No,3500,0,81,300,1,Semiurban,Y
LP001250,Male,Yes,3+,Not Graduate,No,4755,0,95,,0,Semiurban,N
LP001253,Male,Yes,3+,Graduate,Yes,5266,1774,187,360,1,Semiurban,Y
LP001255,Male,No,0,Graduate,No,3750,0,113,480,1,Urban,N
LP001256,Male,No,0,Graduate,No,3750,4750,176,360,1,Urban,N
LP001259,Male,Yes,1,Graduate,Yes,1000,3022,110,360,1,Urban,N
LP001263,Male,Yes,3+,Graduate,No,3167,4000,180,300,0,Semiurban,N
LP001264,Male,Yes,3+,Not Graduate,Yes,3333,2166,130,360,,Semiurban,Y
LP001265,Female,No,0,Graduate,No,3846,0,111,360,1,Semiurban,Y
LP001266,Male,Yes,1,Graduate,Yes,2395,0,,360,1,Semiurban,Y
LP001267,Female,Yes,2,Graduate,No,1378,1881,167,360,1,Urban,N
LP001273,Male,Yes,0,Graduate,No,6000,2250,265,360,,Semiurban,N
LP001275,Male,Yes,1,Graduate,No,3988,0,50,240,1,Urban,Y
LP001279,Male,No,0,Graduate,No,2366,2531,136,360,1,Semiurban,Y
LP001280,Male,Yes,2,Not Graduate,No,3333,2000,99,360,,Semiurban,Y
LP001282,Male,Yes,0,Graduate,No,2500,2118,104,360,1,Semiurban,Y
LP001289,Male,No,0,Graduate,No,8566,0,210,360,1,Urban,Y
LP001310,Male,Yes,0,Graduate,No,5695,4167,175,360,1,Semiurban,Y
LP001316,Male,Yes,0,Graduate,No,2958,2900,131,360,1,Semiurban,Y
LP001318,Male,Yes,2,Graduate,No,6250,5654,188,180,1,Semiurban,Y
LP001319,Male,Yes,2,Not Graduate,No,3273,1820,81,360,1,Urban,Y
LP001322,Male,No,0,Graduate,No,4133,0,122,360,1,Semiurban,Y
LP001325,Male,No,0,Not Graduate,No,3620,0,25,120,1,Semiurban,Y
LP001326,Male,No,0,Graduate,,6782,0,,360,,Urban,N
LP001327,Female,Yes,0,Graduate,No,2484,2302,137,360,1,Semiurban,Y
LP001333,Male,Yes,0,Graduate,No,1977,997,50,360,1,Semiurban,Y
LP001334,Male,Yes,0,Not Graduate,No,4188,0,115,180,1,Semiurban,Y
LP001343,Male,Yes,0,Graduate,No,1759,3541,131,360,1,Semiurban,Y
LP001345,Male,Yes,2,Not Graduate,No,4288,3263,133,180,1,Urban,Y
LP001349,Male,No,0,Graduate,No,4843,3806,151,360,1,Semiurban,Y
LP001350,Male,Yes,,Graduate,No,13650,0,,360,1,Urban,Y
LP001356,Male,Yes,0,Graduate,No,4652,3583,,360,1,Semiurban,Y
LP001357,Male,,,Graduate,No,3816,754,160,360,1,Urban,Y
LP001367,Male,Yes,1,Graduate,No,3052,1030,100,360,1,Urban,Y
LP001369,Male,Yes,2,Graduate,No,11417,1126,225,360,1,Urban,Y
LP001370,Male,No,0,Not Graduate,,7333,0,120,360,1,Rural,N
LP001379,Male,Yes,2,Graduate,No,3800,3600,216,360,0,Urban,N
LP001384,Male,Yes,3+,Not Graduate,No,2071,754,94,480,1,Semiurban,Y
LP001385,Male,No,0,Graduate,No,5316,0,136,360,1,Urban,Y
LP001387,Female,Yes,0,Graduate,,2929,2333,139,360,1,Semiurban,Y
LP001391,Male,Yes,0,Not Graduate,No,3572,4114,152,,0,Rural,N
LP001392,Female,No,1,Graduate,Yes,7451,0,,360,1,Semiurban,Y
LP001398,Male,No,0,Graduate,,5050,0,118,360,1,Semiurban,Y
LP001401,Male,Yes,1,Graduate,No,14583,0,185,180,1,Rural,Y
LP001404,Female,Yes,0,Graduate,No,3167,2283,154,360,1,Semiurban,Y
LP001405,Male,Yes,1,Graduate,No,2214,1398,85,360,,Urban,Y
LP001421,Male,Yes,0,Graduate,No,5568,2142,175,360,1,Rural,N
LP001422,Female,No,0,Graduate,No,10408,0,259,360,1,Urban,Y
LP001426,Male,Yes,,Graduate,No,5667,2667,180,360,1,Rural,Y
LP001430,Female,No,0,Graduate,No,4166,0,44,360,1,Semiurban,Y
LP001431,Female,No,0,Graduate,No,2137,8980,137,360,0,Semiurban,Y
LP001432,Male,Yes,2,Graduate,No,2957,0,81,360,1,Semiurban,Y
LP001439,Male,Yes,0,Not Graduate,No,4300,2014,194,360,1,Rural,Y
LP001443,Female,No,0,Graduate,No,3692,0,93,360,,Rural,Y
LP001448,,Yes,3+,Graduate,No,23803,0,370,360,1,Rural,Y
LP001449,Male,No,0,Graduate,No,3865,1640,,360,1,Rural,Y
LP001451,Male,Yes,1,Graduate,Yes,10513,3850,160,180,0,Urban,N
LP001465,Male,Yes,0,Graduate,No,6080,2569,182,360,,Rural,N
LP001469,Male,No,0,Graduate,Yes,20166,0,650,480,,Urban,Y
LP001473,Male,No,0,Graduate,No,2014,1929,74,360,1,Urban,Y
LP001478,Male,No,0,Graduate,No,2718,0,70,360,1,Semiurban,Y
LP001482,Male,Yes,0,Graduate,Yes,3459,0,25,120,1,Semiurban,Y
LP001487,Male,No,0,Graduate,No,4895,0,102,360,1,Semiurban,Y
LP001488,Male,Yes,3+,Graduate,No,4000,7750,290,360,1,Semiurban,N
LP001489,Female,Yes,0,Graduate,No,4583,0,84,360,1,Rural,N
LP001491,Male,Yes,2,Graduate,Yes,3316,3500,88,360,1,Urban,Y
LP001492,Male,No,0,Graduate,No,14999,0,242,360,0,Semiurban,N
LP001493,Male,Yes,2,Not Graduate,No,4200,1430,129,360,1,Rural,N
LP001497,Male,Yes,2,Graduate,No,5042,2083,185,360,1,Rural,N
LP001498,Male,No,0,Graduate,No,5417,0,168,360,1,Urban,Y
LP001504,Male,No,0,Graduate,Yes,6950,0,175,180,1,Semiurban,Y
LP001507,Male,Yes,0,Graduate,No,2698,2034,122,360,1,Semiurban,Y
LP001508,Male,Yes,2,Graduate,No,11757,0,187,180,1,Urban,Y
LP001514,Female,Yes,0,Graduate,No,2330,4486,100,360,1,Semiurban,Y
LP001516,Female,Yes,2,Graduate,No,14866,0,70,360,1,Urban,Y
LP001518,Male,Yes,1,Graduate,No,1538,1425,30,360,1,Urban,Y
LP001519,Female,No,0,Graduate,No,10000,1666,225,360,1,Rural,N
LP001520,Male,Yes,0,Graduate,No,4860,830,125,360,1,Semiurban,Y
LP001528,Male,No,0,Graduate,No,6277,0,118,360,0,Rural,N
LP001529,Male,Yes,0,Graduate,Yes,2577,3750,152,360,1,Rural,Y
LP001531,Male,No,0,Graduate,No,9166,0,244,360,1,Urban,N
LP001532,Male,Yes,2,Not Graduate,No,2281,0,113,360,1,Rural,N
LP001535,Male,No,0,Graduate,No,3254,0,50,360,1,Urban,Y
LP001536,Male,Yes,3+,Graduate,No,39999,0,600,180,0,Semiurban,Y
LP001541,Male,Yes,1,Graduate,No,6000,0,160,360,,Rural,Y
LP001543,Male,Yes,1,Graduate,No,9538,0,187,360,1,Urban,Y
LP001546,Male,No,0,Graduate,,2980,2083,120,360,1,Rural,Y
LP001552,Male,Yes,0,Graduate,No,4583,5625,255,360,1,Semiurban,Y
LP001560,Male,Yes,0,Not Graduate,No,1863,1041,98,360,1,Semiurban,Y
LP001562,Male,Yes,0,Graduate,No,7933,0,275,360,1,Urban,N
LP001565,Male,Yes,1,Graduate,No,3089,1280,121,360,0,Semiurban,N
LP001570,Male,Yes,2,Graduate,No,4167,1447,158,360,1,Rural,Y
LP001572,Male,Yes,0,Graduate,No,9323,0,75,180,1,Urban,Y
LP001574,Male,Yes,0,Graduate,No,3707,3166,182,,1,Rural,Y
LP001577,Female,Yes,0,Graduate,No,4583,0,112,360,1,Rural,N
LP001578,Male,Yes,0,Graduate,No,2439,3333,129,360,1,Rural,Y
LP001579,Male,No,0,Graduate,No,2237,0,63,480,0,Semiurban,N
LP001580,Male,Yes,2,Graduate,No,8000,0,200,360,1,Semiurban,Y
LP001581,Male,Yes,0,Not Graduate,,1820,1769,95,360,1,Rural,Y
LP001585,,Yes,3+,Graduate,No,51763,0,700,300,1,Urban,Y
LP001586,Male,Yes,3+,Not Graduate,No,3522,0,81,180,1,Rural,N
LP001594,Male,Yes,0,Graduate,No,5708,5625,187,360,1,Semiurban,Y
LP001603,Male,Yes,0,Not Graduate,Yes,4344,736,87,360,1,Semiurban,N
LP001606,Male,Yes,0,Graduate,No,3497,1964,116,360,1,Rural,Y
LP001608,Male,Yes,2,Graduate,No,2045,1619,101,360,1,Rural,Y
LP001610,Male,Yes,3+,Graduate,No,5516,11300,495,360,0,Semiurban,N
LP001616,Male,Yes,1,Graduate,No,3750,0,116,360,1,Semiurban,Y
LP001630,Male,No,0,Not Graduate,No,2333,1451,102,480,0,Urban,N
LP001633,Male,Yes,1,Graduate,No,6400,7250,180,360,0,Urban,N
LP001634,Male,No,0,Graduate,No,1916,5063,67,360,,Rural,N
LP001636,Male,Yes,0,Graduate,No,4600,0,73,180,1,Semiurban,Y
LP001637,Male,Yes,1,Graduate,No,33846,0,260,360,1,Semiurban,N
LP001639,Female,Yes,0,Graduate,No,3625,0,108,360,1,Semiurban,Y
LP001640,Male,Yes,0,Graduate,Yes,39147,4750,120,360,1,Semiurban,Y
LP001641,Male,Yes,1,Graduate,Yes,2178,0,66,300,0,Rural,N
LP001643,Male,Yes,0,Graduate,No,2383,2138,58,360,,Rural,Y
LP001644,,Yes,0,Graduate,Yes,674,5296,168,360,1,Rural,Y
LP001647,Male,Yes,0,Graduate,No,9328,0,188,180,1,Rural,Y
LP001653,Male,No,0,Not Graduate,No,4885,0,48,360,1,Rural,Y
LP001656,Male,No,0,Graduate,No,12000,0,164,360,1,Semiurban,N
LP001657,Male,Yes,0,Not Graduate,No,6033,0,160,360,1,Urban,N
LP001658,Male,No,0,Graduate,No,3858,0,76,360,1,Semiurban,Y
LP001664,Male,No,0,Graduate,No,4191,0,120,360,1,Rural,Y
LP001665,Male,Yes,1,Graduate,No,3125,2583,170,360,1,Semiurban,N
LP001666,Male,No,0,Graduate,No,8333,3750,187,360,1,Rural,Y
LP001669,Female,No,0,Not Graduate,No,1907,2365,120,,1,Urban,Y
LP001671,Female,Yes,0,Graduate,No,3416,2816,113,360,,Semiurban,Y
LP001673,Male,No,0,Graduate,Yes,11000,0,83,360,1,Urban,N
LP001674,Male,Yes,1,Not Graduate,No,2600,2500,90,360,1,Semiurban,Y
LP001677,Male,No,2,Graduate,No,4923,0,166,360,0,Semiurban,Y
LP001682,Male,Yes,3+,Not Graduate,No,3992,0,,180,1,Urban,N
LP001688,Male,Yes,1,Not Graduate,No,3500,1083,135,360,1,Urban,Y
LP001691,Male,Yes,2,Not Graduate,No,3917,0,124,360,1,Semiurban,Y
LP001692,Female,No,0,Not Graduate,No,4408,0,120,360,1,Semiurban,Y
LP001693,Female,No,0,Graduate,No,3244,0,80,360,1,Urban,Y
LP001698,Male,No,0,Not Graduate,No,3975,2531,55,360,1,Rural,Y
LP001699,Male,No,0,Graduate,No,2479,0,59,360,1,Urban,Y
LP001702,Male,No,0,Graduate,No,3418,0,127,360,1,Semiurban,N
LP001708,Female,No,0,Graduate,No,10000,0,214,360,1,Semiurban,N
LP001711,Male,Yes,3+,Graduate,No,3430,1250,128,360,0,Semiurban,N
LP001713,Male,Yes,1,Graduate,Yes,7787,0,240,360,1,Urban,Y
LP001715,Male,Yes,3+,Not Graduate,Yes,5703,0,130,360,1,Rural,Y
LP001716,Male,Yes,0,Graduate,No,3173,3021,137,360,1,Urban,Y
LP001720,Male,Yes,3+,Not Graduate,No,3850,983,100,360,1,Semiurban,Y
LP001722,Male,Yes,0,Graduate,No,150,1800,135,360,1,Rural,N
LP001726,Male,Yes,0,Graduate,No,3727,1775,131,360,1,Semiurban,Y
LP001732,Male,Yes,2,Graduate,,5000,0,72,360,0,Semiurban,N
LP001734,Female,Yes,2,Graduate,No,4283,2383,127,360,,Semiurban,Y
LP001736,Male,Yes,0,Graduate,No,2221,0,60,360,0,Urban,N
LP001743,Male,Yes,2,Graduate,No,4009,1717,116,360,1,Semiurban,Y
LP001744,Male,No,0,Graduate,No,2971,2791,144,360,1,Semiurban,Y
LP001749,Male,Yes,0,Graduate,No,7578,1010,175,,1,Semiurban,Y
LP001750,Male,Yes,0,Graduate,No,6250,0,128,360,1,Semiurban,Y
LP001751,Male,Yes,0,Graduate,No,3250,0,170,360,1,Rural,N
LP001754,Male,Yes,,Not Graduate,Yes,4735,0,138,360,1,Urban,N
LP001758,Male,Yes,2,Graduate,No,6250,1695,210,360,1,Semiurban,Y
LP001760,Male,,,Graduate,No,4758,0,158,480,1,Semiurban,Y
LP001761,Male,No,0,Graduate,Yes,6400,0,200,360,1,Rural,Y
LP001765,Male,Yes,1,Graduate,No,2491,2054,104,360,1,Semiurban,Y
LP001768,Male,Yes,0,Graduate,,3716,0,42,180,1,Rural,Y
LP001770,Male,No,0,Not Graduate,No,3189,2598,120,,1,Rural,Y
LP001776,Female,No,0,Graduate,No,8333,0,280,360,1,Semiurban,Y
LP001778,Male,Yes,1,Graduate,No,3155,1779,140,360,1,Semiurban,Y
LP001784,Male,Yes,1,Graduate,No,5500,1260,170,360,1,Rural,Y
LP001786,Male,Yes,0,Graduate,,5746,0,255,360,,Urban,N
LP001788,Female,No,0,Graduate,Yes,3463,0,122,360,,Urban,Y
LP001790,Female,No,1,Graduate,No,3812,0,112,360,1,Rural,Y
LP001792,Male,Yes,1,Graduate,No,3315,0,96,360,1,Semiurban,Y
LP001798,Male,Yes,2,Graduate,No,5819,5000,120,360,1,Rural,Y
LP001800,Male,Yes,1,Not Graduate,No,2510,1983,140,180,1,Urban,N
LP001806,Male,No,0,Graduate,No,2965,5701,155,60,1,Urban,Y
LP001807,Male,Yes,2,Graduate,Yes,6250,1300,108,360,1,Rural,Y
LP001811,Male,Yes,0,Not Graduate,No,3406,4417,123,360,1,Semiurban,Y
LP001813,Male,No,0,Graduate,Yes,6050,4333,120,180,1,Urban,N
LP001814,Male,Yes,2,Graduate,No,9703,0,112,360,1,Urban,Y
LP001819,Male,Yes,1,Not Graduate,No,6608,0,137,180,1,Urban,Y
LP001824,Male,Yes,1,Graduate,No,2882,1843,123,480,1,Semiurban,Y
LP001825,Male,Yes,0,Graduate,No,1809,1868,90,360,1,Urban,Y
LP001835,Male,Yes,0,Not Graduate,No,1668,3890,201,360,0,Semiurban,N
LP001836,Female,No,2,Graduate,No,3427,0,138,360,1,Urban,N
LP001841,Male,No,0,Not Graduate,Yes,2583,2167,104,360,1,Rural,Y
LP001843,Male,Yes,1,Not Graduate,No,2661,7101,279,180,1,Semiurban,Y
LP001844,Male,No,0,Graduate,Yes,16250,0,192,360,0,Urban,N
LP001846,Female,No,3+,Graduate,No,3083,0,255,360,1,Rural,Y
LP001849,Male,No,0,Not Graduate,No,6045,0,115,360,0,Rural,N
LP001854,Male,Yes,3+,Graduate,No,5250,0,94,360,1,Urban,N
LP001859,Male,Yes,0,Graduate,No,14683,2100,304,360,1,Rural,N
LP001864,Male,Yes,3+,Not Graduate,No,4931,0,128,360,,Semiurban,N
LP001865,Male,Yes,1,Graduate,No,6083,4250,330,360,,Urban,Y
LP001868,Male,No,0,Graduate,No,2060,2209,134,360,1,Semiurban,Y
LP001870,Female,No,1,Graduate,No,3481,0,155,36,1,Semiurban,N
LP001871,Female,No,0,Graduate,No,7200,0,120,360,1,Rural,Y
LP001872,Male,No,0,Graduate,Yes,5166,0,128,360,1,Semiurban,Y
LP001875,Male,No,0,Graduate,No,4095,3447,151,360,1,Rural,Y
LP001877,Male,Yes,2,Graduate,No,4708,1387,150,360,1,Semiurban,Y
LP001882,Male,Yes,3+,Graduate,No,4333,1811,160,360,0,Urban,Y
LP001883,Female,No,0,Graduate,,3418,0,135,360,1,Rural,N
LP001884,Female,No,1,Graduate,No,2876,1560,90,360,1,Urban,Y
LP001888,Female,No,0,Graduate,No,3237,0,30,360,1,Urban,Y
LP001891,Male,Yes,0,Graduate,No,11146,0,136,360,1,Urban,Y
LP001892,Male,No,0,Graduate,No,2833,1857,126,360,1,Rural,Y
LP001894,Male,Yes,0,Graduate,No,2620,2223,150,360,1,Semiurban,Y
LP001896,Male,Yes,2,Graduate,No,3900,0,90,360,1,Semiurban,Y
LP001900,Male,Yes,1,Graduate,No,2750,1842,115,360,1,Semiurban,Y
LP001903,Male,Yes,0,Graduate,No,3993,3274,207,360,1,Semiurban,Y
LP001904,Male,Yes,0,Graduate,No,3103,1300,80,360,1,Urban,Y
LP001907,Male,Yes,0,Graduate,No,14583,0,436,360,1,Semiurban,Y
LP001908,Female,Yes,0,Not Graduate,No,4100,0,124,360,,Rural,Y
LP001910,Male,No,1,Not Graduate,Yes,4053,2426,158,360,0,Urban,N
LP001914,Male,Yes,0,Graduate,No,3927,800,112,360,1,Semiurban,Y
LP001915,Male,Yes,2,Graduate,No,2301,985.7999878,78,180,1,Urban,Y
LP001917,Female,No,0,Graduate,No,1811,1666,54,360,1,Urban,Y
LP001922,Male,Yes,0,Graduate,No,20667,0,,360,1,Rural,N
LP001924,Male,No,0,Graduate,No,3158,3053,89,360,1,Rural,Y
LP001925,Female,No,0,Graduate,Yes,2600,1717,99,300,1,Semiurban,N
LP001926,Male,Yes,0,Graduate,No,3704,2000,120,360,1,Rural,Y
LP001931,Female,No,0,Graduate,No,4124,0,115,360,1,Semiurban,Y
LP001935,Male,No,0,Graduate,No,9508,0,187,360,1,Rural,Y
LP001936,Male,Yes,0,Graduate,No,3075,2416,139,360,1,Rural,Y
LP001938,Male,Yes,2,Graduate,No,4400,0,127,360,0,Semiurban,N
LP001940,Male,Yes,2,Graduate,No,3153,1560,134,360,1,Urban,Y
LP001945,Female,No,,Graduate,No,5417,0,143,480,0,Urban,N
LP001947,Male,Yes,0,Graduate,No,2383,3334,172,360,1,Semiurban,Y
LP001949,Male,Yes,3+,Graduate,,4416,1250,110,360,1,Urban,Y
LP001953,Male,Yes,1,Graduate,No,6875,0,200,360,1,Semiurban,Y
LP001954,Female,Yes,1,Graduate,No,4666,0,135,360,1,Urban,Y
LP001955,Female,No,0,Graduate,No,5000,2541,151,480,1,Rural,N
LP001963,Male,Yes,1,Graduate,No,2014,2925,113,360,1,Urban,N
LP001964,Male,Yes,0,Not Graduate,No,1800,2934,93,360,0,Urban,N
LP001972,Male,Yes,,Not Graduate,No,2875,1750,105,360,1,Semiurban,Y
LP001974,Female,No,0,Graduate,No,5000,0,132,360,1,Rural,Y
LP001977,Male,Yes,1,Graduate,No,1625,1803,96,360,1,Urban,Y
LP001978,Male,No,0,Graduate,No,4000,2500,140,360,1,Rural,Y
LP001990,Male,No,0,Not Graduate,No,2000,0,,360,1,Urban,N
LP001993,Female,No,0,Graduate,No,3762,1666,135,360,1,Rural,Y
LP001994,Female,No,0,Graduate,No,2400,1863,104,360,0,Urban,N
LP001996,Male,No,0,Graduate,No,20233,0,480,360,1,Rural,N
LP001998,Male,Yes,2,Not Graduate,No,7667,0,185,360,,Rural,Y
LP002002,Female,No,0,Graduate,No,2917,0,84,360,1,Semiurban,Y
LP002004,Male,No,0,Not Graduate,No,2927,2405,111,360,1,Semiurban,Y
LP002006,Female,No,0,Graduate,No,2507,0,56,360,1,Rural,Y
LP002008,Male,Yes,2,Graduate,Yes,5746,0,144,84,,Rural,Y
LP002024,,Yes,0,Graduate,No,2473,1843,159,360,1,Rural,N
LP002031,Male,Yes,1,Not Graduate,No,3399,1640,111,180,1,Urban,Y
LP002035,Male,Yes,2,Graduate,No,3717,0,120,360,1,Semiurban,Y
LP002036,Male,Yes,0,Graduate,No,2058,2134,88,360,,Urban,Y
LP002043,Female,No,1,Graduate,No,3541,0,112,360,,Semiurban,Y
LP002050,Male,Yes,1,Graduate,Yes,10000,0,155,360,1,Rural,N
LP002051,Male,Yes,0,Graduate,No,2400,2167,115,360,1,Semiurban,Y
LP002053,Male,Yes,3+,Graduate,No,4342,189,124,360,1,Semiurban,Y
LP002054,Male,Yes,2,Not Graduate,No,3601,1590,,360,1,Rural,Y
LP002055,Female,No,0,Graduate,No,3166,2985,132,360,,Rural,Y
LP002065,Male,Yes,3+,Graduate,No,15000,0,300,360,1,Rural,Y
LP002067,Male,Yes,1,Graduate,Yes,8666,4983,376,360,0,Rural,N
LP002068,Male,No,0,Graduate,No,4917,0,130,360,0,Rural,Y

In [13]:
data=pd.read_csv('./train.csv')
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [15]:
data.shape

(614, 13)

In [16]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [17]:
data.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [19]:
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [20]:
data['Dependents'].value_counts()

Dependents
0     345
1     102
2     101
3+     51
Name: count, dtype: int64

In [23]:
data=data.drop('Loan_ID',axis=1)
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [24]:
data.describe()
#only numeric features

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [25]:
data.describe(include=['object'])
#categorical features

,Gender,Married,Dependents,Education,Self_Employed,Property_Area,Loan_Status
count,601,611,599,614,582,614,614
unique,2,2,4,2,2,3,2
top,Male,Yes,0,Graduate,No,Semiurban,Y
freq,489,398,345,480,500,233,422

In [26]:
#missing values
data.isna()

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,False,False,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
609,False,False,False,False,False,False,False,False,False,False,False,False
610,False,False,False,False,False,False,False,False,False,False,False,False
611,False,False,False,False,False,False,False,False,False,False,False,False
612,False,False,False,False,False,False,False,False,False,False,False,False
613,False,False,False,False,False,False,False,False,False,False,False,False

In [28]:
data.isna().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [31]:
missing_count=data.isna().sum()
missing_count

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64